spring:
  datasource:
    username: root
    password: MiMa@6462
    url: jdbc:mysql://1.116.135.204:3306/ojdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.oj.ojbackend.pojo
  mapper-locations: mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
